### ISSUE TITLE
Retrieve account transfer returns dates, no datetimes

### ISSUE THREAD

**Issue by techkey** [openMF/mifosx#1329] opened 2015-04-02 03:44 UTC
Hi,

The `JSON` object of retrieve account transfer, `GET https://DomainName/api/v1/accounttransfers/{transferId}`, returns only dates. And the timeline object returned by some (I think most, if not all) `JSON` objects are returning dates only too.

The `m_savings_account_transaction` table has a `created_date` field which is of type `datetime`, but that field doesn't get included in the `JSON` object.

Is this by design? Is there a easy way to make all, or at least the transfer objects, returning the datetime also? 

Cornelis.

**Comment by vishwasbabu** [comment] 2015-04-04 01:52
Hey @techkey .

Some of it is by design, most of the fields like the effective transaction dates on loan and savings are *date* (not *datetime*) . The reason being that when we elicited requirements from the mifos community, the time part of transactions did not have a significance ( a banker would only care about the date on which a loan was disbursed or a repayment was made or a savings withdrawal was made, the time at which these transactions occurred were not needed for processing any of the domain rules). 

However, if you have any use case wherein the effective time of a transaction also needs to be captured, a code change would be required (DB columns need to be updated to *datetime*, create/update api's need to be updated to send *datetime* etc) . For account transfers, I can understand why you would want this change, if you are looking to pick this up, we would be happy to help you out. You could also try raising a ticket on https://mifosforge.jira.com/secure/Dashboard.jspa with your requirements (it just might get picked up by a volunteer)

Of course, the time at which data entry is made into the system is important. API's like https://demo.openmf.org/api-docs/apiLive.htm#makercheckers_list which return details of update/create/delete operations do return datetime fields. Our approach has been to do away with adding created_date_time, updated_date_time to each table and consolidate them in *m_portfolio_command_source* table instead , this table logs all create/post and update/put/delete operations in the system and is used for implement maker-checker functionality across our API's

The example you cite (*created_date* in *m_savings_account_transaction*) is an anomaly, the result of a  recent change for easing reporting (avoiding having to make a joint between transaction tables and m_portfolio_command_source table). Should you choose to be returning this particular date-time, the change required is trivial

**Comment by techkey** [comment] 2015-06-17 08:18
Hi @vishwasbabu 

Thanks for your detailed explanation, it took me a while to get my head around it. Having `datetime` fields is definitely a must for me so I've started to work on that. Soon I fork this project and put the changes in it. Of course I run all tests after every change. If I run into some serious things from I believe it can be solved easier then my way I might ask here if that's alright.

Maybe of topic but are there plans to update the used libraries (and gradle) any time soon?

Thanks again for the insight.

**Comment by vishwasbabu** [comment] 2015-06-20 17:39
@techkey 

>> If I run into some serious things from I believe it can be solved easier then my way I might ask here if that's alright.

Definitely. The best place to get help would be on our mailing lists at https://lists.sourceforge.net/lists/listinfo/mifos-developer

>>Maybe of topic but are there plans to update the used libraries (and gradle) any time soon?

We do not have any plans for updating dependencies in the next couple of months. Please feel free to send a pr across if you have made an updates at your end

**Comment by vorburger** [comment] 2019-02-04 14:55
@techkey thank you for your interest in Mifos. This Git repository is no longer actively maintained, but we would love to see your contributions over in https://github.com/apache/fineract, which is the exact same code as this one. 

Just FYI, that apache/fineract project doesn't use Git Hub Issues but instead they use issues in the FINERACT project in the Apache JIRA, here: https://issues.apache.org/jira. You may also be interested in having a look at http://fineract.apache.org for a better overview and more resources.

I'm closing this old open issue to avoid any future confusion to others.

/Cc FYI @openMF/admins @openMF/core-team @meonkeys @myrle-krantz

**Closed by vorburger** 2019-02-04 14:55 UTC
